# Generated by Django 4.0.8 on 2022-11-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='email',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='asin',
            new_name='product_id',
        ),
    ]
